### ISSUE TITLE
Add support for cross-partition queries.

### ISSUE THREAD

**Issue by pabravil** [jmolla31/Cosmy#1]
## Description

Cosmos document client lets you create cross partition queries via FeedOptions.EnableCrossPartitionQuery =true. 
There is no way to do this with this wrapper. The existing method to create queries fails when the optional _partitionKey_ param is null.

Suggestions: 

- Fix the existing _CreateDocumentQuery<T>(string collection, object partitionKey = null)_
- Add an overload to the existing CreateDocumentQuery<T> method with FeedOptions as a required parameter. _CreateDocumentQuery<T>(string collection, FeedOptions feedOptions)_

## Expected Behavior

Calling _CreateDocumentQuery<T>(string collection, object partitionKey = null)_ without specifying partition key should perform a cross-partition query.

## Actual Behavior

Calling _CreateDocumentQuery<T>(string collection, object partitionKey = null)_ without specifying partition key results in an Exception

_Exception while executing function: CheckNickname. Microsoft.Azure.DocumentDB.Core: Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception._

## Specifications

  - Version: Cosmy v1.2.0

**Comment by jmolla31** [comment]
PR was successfully merged, closing the issue. 

Thx @pabravil 🚀

**Comment by jmolla31** [comment]
PR was successfully merged, closing the issue. 

Thx @pabravil 🚀
